openapi: 3.1.1
info:
  title: Sentinel Auth Backend
  version: 0.0.1
paths:
  /.well-known/jwks.json:
    get:
      summary: 
  /user/authorize:
  /user/token:
  /user/revoke:
  /user/userinfo:
  /user/logout:
  /user/refresh:
  /admin/revoke:
  /admin/delete-user:
  /admin/verify:
  /admin/logout-user:
  /admin/userinfo: