openapi: 3.1.1
info:
  title: Sentinel Auth Backend
  version: 0.0.1
paths:
  /auth/providers:
    get:
      summary: Get all available providers that a user can sign in with by client id
      parameters:
        - name: client_id
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successfully fetched providers
          content:
            application/json:
              schema:
              type: array
              items:
                $ref: '#/components/schemas/StrippedClientProvider'
components:
  schemas:
    StrippedClientProvider:
      type: object
      properties:
        id:
          type: string
        client_id:
          type: string
        provider_option:
          type: object
          properties:
            id:
              type: string
            name:
              type: string
            logo_url:
              type: string
            description:
              type: string
        data: {}